name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test, Lint
        env:
          URL: ${{ secrets.URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          CORPORATE_ID: ${{ secrets.CORPORATE_ID }}
          ORIGIN_HOST: ${{ secrets.ORIGIN_HOST }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CREDENTIAL_ID: ${{ secrets.CREDENTIAL_ID }}
          LOG_PATH: ${{ secrets.LOG_PATH }}
        run: make ci
